### ISSUE TITLE
login page seems to have changed

### ISSUE THREAD

**Issue by stedy** [mattdodge/nyt-crossword-stats#12]
https://myaccount.nytimes.com/svc/ios/v2/login is giving me a [HTTP 405 error](https://http.cat/405) at the moment (HTTP 405 on Chrome, blank page on Firefox)

My guess is the login page has shifted - I will try to poke around and see if I can come up with a fix but just wanted to give you a heads up

**Comment by mattdodge** [comment]
That endpoint will only accept HTTP POST requests. If you hit it with a GET, as in from your browser, you will get the HTTP 405 error. That error tells you that the provided "method" (i.e., http verb) is not supported for that endpoint ([docs here for more info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)).

Just tried a POST from my side and it appears to be working fine, so going to close this issue out

**Comment by stedy** [comment]
Ok looks like I should have been more explicit
I am getting a HTTP 403 error when I try to login via `fetch_puzzle_stats.py`:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myaccount.nytimes.com/svc/ios/v2/login`

My guess is that I tried that url in a browser and hence the HTTP 405 error. Regardless, thanks for looking into this!

**Comment by mattdodge** [comment]
Ah gotcha - yeah the 403 means the username/password is probably invalid. Or it's possible it's being limited by the NYT auth API. This can happen if the requests are originating from a shared machine or a cloud server - are you running this locally or on AWS or some other cloud environment?
