### ISSUE TITLE
login troubles

### ISSUE THREAD

**Issue by xylar** [mattdodge/nyt-crossword-stats#3]
@mattdodge, this looks really cool, like just what I'm looking for.  However, something seems to have changed in the login URL and I can't reach:
https://myaccount.nytimes.com/svc/ios/v2/login
```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myaccount.nytimes.com/svc/ios/v2/login
```
If you have the time/interest, could you check if this URL needs to be updated?

It's also possible that this URL is only accessible from iOS and I'm trying to get there from Linux.

**Comment by mattdodge** [comment]
Good catch! Looks like they have started blocking the default User-Agent that comes with requests. I have updated so if you pull a fresh copy you should be able to run it now.

**Comment by xylar** [comment]
Ah, thanks!  This does seem to fix the issue for me.

**Comment by kyledeanreinford** [comment]
I'm getting this same 403 error after running it with cron without any issues for several months, so I know it's not the login. Something changed with the login portal, I'm guessing.

Seems to have stopped working on October 8th for me (I built a [mini times scraper](https://github.com/kyledeanreinford/NYT_Mini_Leaderboard_Scraper) using your login function and my last successful stat scrape was for the 7th). 

When I try putting my username/password into your site, it seems to have an issue as well.
