### ISSUE TITLE
API gate changed again?

### ISSUE THREAD

**Issue by MichaelChirico** [mattdodge/nyt-crossword-stats#5]
Same issue description as #3 basically:

```
python fetch_puzzle_stats.py -u $USER_NAME -p $PASSWORD --start-date 1993-01-01

Traceback (most recent call last):
  File "fetch_puzzle_stats.py", line 98, in <module>
    cookie = login(args.username, args.password)
  File "fetch_puzzle_stats.py", line 52, in login
    login_resp.raise_for_status()
  File "/home/michael/.local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myaccount.nytimes.com/svc/ios/v2/login
```

Any new workaround, or has this approach been deprecated?

**Comment by mattdodge** [comment]
Hmm I'm unable to reproduce that error. It's working fine for me on latest master branch. That is the same error you will get if your username or password are wrong though, is it possible one of those is wrong? If there's a space or some weird characters it may not escape properly in your shell. (I should probably make the entry of these fields a bit easier...).

As a reminder, it has to be the email/password you use to log in to the NYT Crossword app

**Comment by MichaelChirico** [comment]
> If there's a space or some weird characters it may not escape properly in your shell.

Ah, that's it indeed! I wrapped it in `"` and now it seems to be running.

I'm not sure there'd be anything you could do on your end, I think a note in the README would be enough.
