### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by MichaelChirico** [mattdodge/nyt-crossword-stats#8]
I'm not able to connect right now. I double-checked my password and ensured proper quoting.

Is the API documented? I don't see it listed at https://developer.nytimes.com/apis, but xwstats.com is still working. The problem with xwstats.com is I'm trying to grab my full 30-year history & going month-by-month is pretty tedious for that.

**Comment by mattdodge** [comment]
The API is not documented I'm afraid. What error message are you getting when trying to connect? Any code snippets or stack traces would help.

Also, sometimes username/password doesn't work and you'll need to [follow the manual link instructions](https://xwstats.com/link)

**Comment by MichaelChirico** [comment]
Hmm just now it works. Maybe I had forgotten to `git pull`. Thanks for responding!
